package de.progex.model;

import java.lang.reflect.Field;
import java.sql.Date;

public class Leave {
	private int leave_id;
	private String status;
	private Date startDate;
	private Date endDate;

	public Leave() {

	}

	public Leave(String status, Date startDate, Date endDate) {
		if (setStatus(status))
			this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public int getLeave_id() {
		return leave_id;
	}

	// Autogenerated
	public void setLeave_id(int leave_id) {
		this.leave_id = leave_id;
	}

	public String getStatus() {
		return status;
	}

	public boolean setStatus(String status) {
		if (status.contains("holiday") | status.contains("business trip")  | status.contains("illness")) {
			this.status = status;
			return true;
		} else {
			System.out.println("setStatus failed, or field musst be filled");
			return false;
		}
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean isVerified() throws IllegalAccessException {
		for (Field f : getClass().getDeclaredFields()) {
			if (f.get(this) == null) {
				return false;
			}
		}
		return true;
	}
}
